import type { FoodItem } from './types';

export const mockFoodItems: FoodItem[] = [
  {
    id: 'item-001',
    name: 'Fresh Apples',
    category: 'Produce',
    weight: 20,
    condition: 'fresh',
    expirationDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    storageTemp: 'refrigerated',
    allergens: [],
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    pickupLocation: {
      latitude: 34.0522,
      longitude: -118.2437,
      address: '123 Main St, Los Angeles, CA',
    },
    status: 'stored',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    donorId: 'donor-1',
    claimToken: 'abc-123',
  },
  {
    id: 'item-002',
    name: 'Canned Beans',
    category: 'Canned Goods',
    weight: 50,
    condition: 'packaged',
    expirationDate: new Date(
      Date.now() + 365 * 24 * 60 * 60 * 1000
    ).toISOString(),
    storageTemp: 'ambient',
    allergens: [],
    dietaryTags: ['vegetarian', 'vegan'],
    pickupLocation: {
      latitude: 34.0522,
      longitude: -118.2437,
      address: '123 Main St, Los Angeles, CA',
    },
    status: 'inspected',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    donorId: 'donor-2',
    claimToken: 'def-456',
  },
  {
    id: 'item-003',
    name: 'Whole Wheat Bread',
    category: 'Bakery',
    weight: 15,
    condition: 'fresh',
    expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    storageTemp: 'ambient',
    allergens: ['gluten', 'wheat'],
    dietaryTags: ['vegetarian'],
    pickupLocation: {
      latitude: 34.0522,
      longitude: -118.2437,
      address: '456 Oak Ave, Los Angeles, CA',
    },
    status: 'allocated',
    recipientId: 'recipient-1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    donorId: 'donor-1',
    claimToken: 'ghi-789',
  },
  {
    id: 'item-004',
    name: 'Frozen Chicken',
    category: 'Meat',
    weight: 30,
    condition: 'frozen',
    expirationDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    storageTemp: 'frozen',
    allergens: [],
    dietaryTags: [],
    pickupLocation: {
      latitude: 34.0522,
      longitude: -118.2437,
      address: '789 Pine St, Los Angeles, CA',
    },
    status: 'picked_up',
    recipientId: 'recipient-2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    donorId: 'donor-3',
    claimToken: 'jkl-012',
  },
  {
    id: 'item-005',
    name: 'Expired Yogurt',
    category: 'Dairy',
    weight: 10,
    condition: 'fresh',
    expirationDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    storageTemp: 'refrigerated',
    allergens: ['dairy'],
    dietaryTags: ['vegetarian'],
    pickupLocation: {
      latitude: 34.0522,
      longitude: -118.2437,
      address: '101 Maple Dr, Los Angeles, CA',
    },
    status: 'expired',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    donorId: 'donor-2',
    claimToken: 'mno-345',
  },
];
